<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

$imagesArray = json_decode($block->getGalleryImagesJson(), true);
?>

<div id="galleryWrapper" data-gallery-role="gallery-placeholder" class="gallery">
    <div class="gallery__close"></div>
    <div class="gallery-top swiper-container gallery__top">
        <div class="swiper-wrapper gallery__slides">
            <?php foreach($imagesArray as $imageData): ?>
                <?php if($imageData['img'] && $imageData['full']): ?>
                    <div class="swiper-slide">
                        <img class="swiper-img" data-img="<?= $imageData['img'] ?>" data-full="<?= $imageData['full'] ?>" src="<?= $imageData['img'] ?>" alt="Slide image" />
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <!-- Add Arrows -->
        <div class="swiper-button-next swiper-button-white gallery__button gallery__button--next"></div>
        <div class="swiper-button-prev swiper-button-white gallery__button gallery__button--prev"></div>

        <div class="swiper-pagination gallery__pagination"></div>
    </div>
    <div class="swiper-container-thumbs gallery__bottom">
        <div class="swiper-wrapper gallery__thumbs"></div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#galleryWrapper": {
            "customGallery": {
                "images": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "thumbsBreakpoint": 1024,
                "options": {
                    "navigation": {
                        "nextEl": ".swiper-button-next",
                        "prevEl": ".swiper-button-prev"
                    },
                    "pagination": {
                        "el": ".swiper-pagination",
                        "type": "bullets",
                        "clickable": true
                    },
                    "thumbs": {
                        "swiper": {
                            "el": ".swiper-container-thumbs",
                            "spaceBetween": 22,
                            "slidesPerView": 4,
                            "watchSlidesVisibility": true,
                            "watchSlidesProgress": true
                        }
                    }
                }
            }
        }
    }
</script>
